# Generated by Django 4.2.7 on 2024-11-25 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_employee_remaining_leave_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_days',
            field=models.FloatField(default=15.0, help_text='Annual leave balance in days'),
        ),
    ]
