# Generated by Django 4.2.7 on 2024-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_employee_annual_leave_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='annual_leave_days',
            field=models.PositiveIntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='employee',
            name='used_leave_days',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
