# Generated by Django 4.2.7 on 2024-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_options_remove_notification_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('late_checkin', 'Late Check-in'), ('leave_reminder', 'Leave Reminder')], default='late_checkin', max_length=20),
        ),
    ]
