# Generated by Django 4.2.7 on 2024-11-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='has_checked_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendance',
            name='has_checked_out',
            field=models.BooleanField(default=False),
        ),
    ]
