# Generated by Django 4.2.7 on 2024-11-25 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendance_has_checked_in_attendance_has_checked_out'),
        ('attendance', '0002_auto_20241126_fix_fields'),
    ]

    operations = [
    ]
