# Generated by Django 4.2.7 on 2024-11-25 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_merge_20241125_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='has_checked_in',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='has_checked_out',
        ),
    ]
