# Generated by Django 4.2.7 on 2024-11-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_check_in_check_out_fields'),
        ('attendance', '0004_remove_attendance_has_checked_in_and_more'),
    ]

    operations = [
    ]
