# Generated by Django 4.2.7 on 2024-11-25 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_merge_20241125_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='check_in',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='check_out',
            field=models.TimeField(null=True),
        ),
    ]
